--------------------------------------------------------
-- Archivo creado  - viernes-octubre-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAPTURAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DCARMONA"."CAPTURAS_SEQ"  MINVALUE 1 MAXVALUE 200 INCREMENT BY 1 START WITH 50 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLASE_EMPLEADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DCARMONA"."CLASE_EMPLEADO_SEQ"  MINVALUE 1 MAXVALUE 700 INCREMENT BY 1 START WITH 500 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CAPTURAS
--------------------------------------------------------

  CREATE TABLE "DCARMONA"."CAPTURAS" 
   (	"ID" NUMBER(*,0), 
	"FECHA" DATE, 
	"DEPARTAMENTO" VARCHAR2(255), 
	"MUNICIPIO" VARCHAR2(255), 
	"DIA" VARCHAR2(255), 
	"BARRIO" VARCHAR2(255), 
	"ZONA" VARCHAR2(255), 
	"CLASE_SITIO" VARCHAR2(255), 
	"EDAD" NUMBER(*,0), 
	"SEXO" VARCHAR2(255), 
	"ESTADO_CIVIL" VARCHAR2(255), 
	"CLASE_EMPLEADO_ID" NUMBER(*,0), 
	"PROFESION" VARCHAR2(255), 
	"ESCOLARIDAD" VARCHAR2(255), 
	"DELITO" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table CLASE_EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "DCARMONA"."CLASE_EMPLEADOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
REM INSERTING into DCARMONA.CAPTURAS
SET DEFINE OFF;
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('500',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','DANGON','URBANA','VIAS PUBLICAS','28','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('501',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','BALNEARIO HURTADO','URBANA','RIOS','19','MASCULINO','SOLTERO','505','0','0','ARTÍCULO 328. ILÍCITO APROVECHAMIENTO DE LOS RECURSOS NATURALES RENOVABLES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('502',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','ALTOS DE PIMIENTA','URBANA','VIAS PUBLICAS','36','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('503',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','ALTOS DE PIMIENTA','URBANA','VIAS PUBLICAS','38','MASCULINO','CASADO','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('504',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','VEREDA','URBANA','VIAS PUBLICAS','19','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('505',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','FUTURO DE LOS NIÑOS','URBANA','VIAS PUBLICAS','22','MASCULINO','UNION LIBRE','502','0','0','ARTÍCULO 365. FABRICACIÓN, TRÁFICO, PORTE O TENENCIA DE ARMAS DE FUEGO,ACCESORIOS, PARTES O MUNICIONES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('506',to_date('01/01/18','DD/MM/RR'),'CESAR','VALLEDUPAR (CT)','Lunes','LOS MUSICOS','URBANA','VIAS PUBLICAS','25','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('507',to_date('01/01/18','DD/MM/RR'),'CHOCÓ','ACANDÍ','Lunes','CGTO. CAPURGANA','RURAL','FINCAS Y SIMILARES','26','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('508',to_date('01/01/18','DD/MM/RR'),'CHOCÓ','LLORÓ','Lunes','La punta','URBANA','VIAS PUBLICAS','17','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('509',to_date('01/01/18','DD/MM/RR'),'CHOCÓ','NÓVITA','Lunes','CAMELLON','URBANA','VIAS PUBLICAS','18','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 365. FABRICACIÓN, TRÁFICO, PORTE O TENENCIA DE ARMAS DE FUEGO,ACCESORIOS, PARTES O MUNICIONES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('510',to_date('01/01/18','DD/MM/RR'),'CHOCÓ','QUIBDÓ (CT)','Lunes','ALAMEDA REYES','URBANA','VIAS PUBLICAS','24','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 447. RECEPTACIÓN');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('511',to_date('01/01/18','DD/MM/RR'),'CÓRDOBA','MONTELÍBANO','Lunes','CENTRO','URBANA','VIAS PUBLICAS','20','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 340. CONCIERTO PARA DELINQUIR');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('512',to_date('01/01/18','DD/MM/RR'),'CÓRDOBA','MONTERÍA (CT)','Lunes','EL PARAISO','URBANA','VIAS PUBLICAS','37','MASCULINO','SOLTERO','506','0','0','ARTÍCULO 340. CONCIERTO PARA DELINQUIR');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('513',to_date('01/01/18','DD/MM/RR'),'CÓRDOBA','MONTERÍA (CT)','Lunes','LA CAMPIÑA','URBANA','VIAS PUBLICAS','44','MASCULINO','UNION LIBRE','500','0','0','ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('514',to_date('01/01/18','DD/MM/RR'),'CÓRDOBA','MONTERÍA (CT)','Lunes','GALILEA','URBANA','VIAS PUBLICAS','42','MASCULINO','SOLTERO','506','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('515',to_date('01/01/18','DD/MM/RR'),'CÓRDOBA','MONTERÍA (CT)','Lunes','EL PARAISO','URBANA','CASAS DE HABITACION','27','MASCULINO','SOLTERO','506','0','0','ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('516',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','VITELMA E-4','URBANA','VIAS PUBLICAS','43','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('517',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','CLASS E-8','URBANA','VIAS PUBLICAS','32','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('518',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','MODELIA E-9','URBANA','VIAS PUBLICAS','20','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('519',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','MODELIA E-9','URBANA','VIAS PUBLICAS','38','MASCULINO','UNION LIBRE','501','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('520',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','POTOSI E-19','URBANA','VIAS PUBLICAS','21','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('521',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','EL RINCÓN E-11','URBANA','VIAS PUBLICAS','39','FEMENINO','SOLTERO','504','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('522',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','ALTAMIRA E-4','URBANA','VIAS PUBLICAS','22','MASCULINO','UNION LIBRE','503','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('523',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','SANTA CECILIA E-9','URBANA','VIAS PUBLICAS','35','MASCULINO','SOLTERO','503','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('524',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','SORATAMA E-1','URBANA','VIAS PUBLICAS','38','FEMENINO','UNION LIBRE','504','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('525',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','TINTAL    E-8','URBANA','VIAS PUBLICAS','34','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('526',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','URB. LA GUACA E-16','URBANA','VIAS PUBLICAS','38','MASCULINO','SOLTERO','503','0','0','ARTÍCULO 448. FUGA DE PRESOS');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('527',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','LA AGUADITA E-11','URBANA','VIAS PUBLICAS','19','MASCULINO','SOLTERO','504','0','0','ARTÍCULO 365. FABRICACIÓN, TRÁFICO, PORTE O TENENCIA DE ARMAS DE FUEGO,ACCESORIOS, PARTES O MUNICIONES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('528',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','JOSE ANTONIO GALAN E-7','URBANA','VIAS PUBLICAS','21','MASCULINO','UNION LIBRE','507','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('529',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','SAN ANTONIO E-15','URBANA','VIAS PUBLICAS','31','MASCULINO','UNION LIBRE','504','0','0','ARTÍCULO 103. HOMICIDIO');
Insert into DCARMONA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO_ID,PROFESION,ESCOLARIDAD,DELITO) values ('530',to_date('01/01/18','DD/MM/RR'),'CUNDINAMARCA','BOGOTÁ D.C. (CT)','Lunes','LA GLORIA E-4','URBANA','VIAS PUBLICAS','40','MASCULINO','SOLTERO','506','0','0','ARTÍCULO 365. FABRICACIÓN, TRÁFICO, PORTE O TENENCIA DE ARMAS DE FUEGO,ACCESORIOS, PARTES O MUNICIONES');
REM INSERTING into DCARMONA.CLASE_EMPLEADOS
SET DEFINE OFF;
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('500','AGRICULTOR');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('501','COMERCIANTE');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('502','CONTRATISTA');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('503','DESEMPLEADO');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('504','EMPLEADO PARTICULAR');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('505','ESTUDIANTE');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('506','INDEPENDIENTE');
Insert into DCARMONA.CLASE_EMPLEADOS (ID,NOMBRE) values ('507','JUBILADO');
--------------------------------------------------------
--  DDL for Index CLASE_EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DCARMONA"."CLASE_EMPLEADOS_PK" ON "DCARMONA"."CLASE_EMPLEADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  Constraints for Table CAPTURAS
--------------------------------------------------------

  ALTER TABLE "DCARMONA"."CAPTURAS" MODIFY ("CLASE_EMPLEADO_ID" NOT NULL ENABLE);
  ALTER TABLE "DCARMONA"."CAPTURAS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASE_EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "DCARMONA"."CLASE_EMPLEADOS" ADD CONSTRAINT "CLASE_EMPLEADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
  ALTER TABLE "DCARMONA"."CLASE_EMPLEADOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CAPTURAS
--------------------------------------------------------

  ALTER TABLE "DCARMONA"."CAPTURAS" ADD CONSTRAINT "FK_CLASE_EMPLEADOS_ID" FOREIGN KEY ("CLASE_EMPLEADO_ID")
	  REFERENCES "DCARMONA"."CLASE_EMPLEADOS" ("ID") ENABLE;
