CREATE TABLESPACE mid_term
DATAFILE '/u01/app/oracle/oradata/XE/mid_term.dbf' SIZE 60M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE USER dcarmona
IDENTIFIED BY dcarmona
DEFAULT TABLESPACE mid_term
QUOTA UNLIMITED ON mid_term;

CREATE ROLE MINI_DBA;
GRANT CONNECT TO MINI_DBA;

GRANT CREATE TABLE TO MINI_DBA;
GRANT CREATE SEQUENCE TO MINI_DBA;

CREATE ROLE STUDENT;
GRANT CONNECT TO STUDENT;
GRANT CREATE SESSION TO STUDENT;

GRANT MINI_DBA TO STUDENT;

GRANT STUDENT TO dcarmona;



