CREATE SEQUENCE CLASE_EMPLEADO_SEQ
START WITH 500
INCREMENT BY 1
MAXVALUE 700;

CREATE SEQUENCE CAPTURAS_SEQ
START WITH 50
INCREMENT BY 1
MAXVALUE 200;

CREATE TABLE CLASE_EMPLEADOS
( 
  ID INTEGER NOT NULL,
  NOMBRE varchar2(255),
  CONSTRAINT CLASE_EMPLEADOS_PK PRIMARY KEY (ID)
);

create table CAPTURAS (
  ID INTEGER NOT NULL,
  FECHA	date,
  DEPARTAMENTO	varchar2(255),
  MUNICIPIO	varchar2(255),
  DIA	varchar2(255),
  BARRIO	varchar2(255),
  ZONA 	varchar2(255),
  CLASE_SITIO	varchar2(255),
  EDAD INTEGER,
  SEXO	varchar2(255),
  ESTADO_CIVIL varchar2(255),
  CLASE_EMPLEADO_ID INTEGER NOT NULL,
  PROFESION varchar2(255),
  ESCOLARIDAD varchar2(255),
  DELITO varchar2(255)
);

ALTER TABLE CAPTURAS
ADD CONSTRAINT FK_CLASE_EMPLEADOS_ID
   FOREIGN KEY (CLASE_EMPLEADO_ID)
   REFERENCES CLASE_EMPLEADOS (ID);



